### ISSUE TITLE
Listen to events on $rootScope

### ISSUE THREAD

**Issue by matheusgrieger** [Kurtz1993/angular-idle-service#3]
I successfully got events when on local $scopes from controllers, but is there a way to get them in the $rootScope as well? I'm writing a service, and would need those events, unless I write a directive that sends those events to the $rootScope, which would not be of my likings.
Thanks, and great service you've made!

**Comment by Kurtz1993** [comment]
It's supposed that the events are being catched by the $rootScope. You can see the example file [here](https://github.com/Kurtz1993/angular-idle-service/blob/master/index.js).

PS: Sorry for the very laaaate response, I haven't been around for a while. Just returning to use github.
