### ISSUE TITLE
New event when user comes back from inactivity

### ISSUE THREAD

**Issue by WillCaprara** [Kurtz1993/angular-idle-service#4]
$userBack event only fires when you are already in "idle state" and not timed out. Is there a way to add a new event that is fired when user actually comes back from inactivity? E.g:
Idle time: 5 mins
User is inactive for 30 seconds... user comes back at second 31... moves mouse/clicks or whatever... fire event.

Thanks

**Comment by Kurtz1993** [comment]
You can now use the "$userActive" event, which will have the time that the user has been idle as a parameter passed to the event.

```javascript
$rootScope.$on('$userActive', function (_, timeIdle) {
    console.log(timeIdle)
    console.log(`You have been idle for ${timeIdle} seconds`);
});
```
