### ISSUE TITLE
Time user has been idle/inactive

### ISSUE THREAD

**Issue by WillCaprara** [Kurtz1993/angular-idle-service#5]
Idle time: 20 mins
System checks every 10 mins for user activity. If the user has been inactive the whole 10 mins... do nothing... if the user was active before the 10 min check... do something...

Is there a way to know how much time a user has been idle/inactive?

Thanks!

**Comment by Kurtz1993** [comment]
There are two ways in which you can see this now.

You can use the `"$userActive"` event, which will have the time that the user has been idle as a parameter passed to the event.
```javascript
$rootScope.$on('$userActive', function (_, timeIdle) {
    console.log(timeIdle)
    console.log(`You have been idle for ${timeIdle} seconds`);
});
```

Or you can get it directly from the idle state by using the IdleService:

```javascript
$idle.getIdleState().userIdleTime
```
